export const GET_PREVIEW = 'GET_PREVIEW';
export const RECIEVE_PREVIEW = 'RECIEVE_PREVIEW';
export const GET_FULL_IMAGE = 'GET_FULL_IMAGE';
export const RECIEVE_FULL_IMAGE = 'RECIEVE_FULL_IMAG';
export const SET_LOADED_FALSE = 'SET_LOADED_FALSE';
export const SETTING_LOADING_FALSE = 'SETTING_LOADING_FALSE';
